<?php

declare(strict_types=1);

namespace App\Http\Controllers\Staff;

use App\Domain\Staff\Actions\UpdateStaffPhotoAction;
use App\Domain\Staff\Models\StaffProfile;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Policy-authorized inline delivery for private staff profile photos.
 *
 * Photos share the private disk with credentials, so an ImageColumn cannot use
 * Storage::url() or a signed storage URL. Every browser image request reaches
 * this controller and re-checks StaffProfilePolicy::view() for the current user.
 */
final class StaffProfilePhotoController extends Controller
{
    public function __invoke(Request $request, StaffProfile $profile): StreamedResponse
    {
        $actor = $request->user();

        if (! $actor instanceof User || ! $actor->is_active) {
            abort(403);
        }

        Gate::forUser($actor)->authorize('view', $profile);

        $path = $profile->profile_photo_path;

        if (! is_string($path) || ! $this->isStaffPhotoPath($path)) {
            abort(404);
        }

        $disk = Storage::disk(UpdateStaffPhotoAction::DISK);

        if (! $disk->exists($path)) {
            abort(404);
        }

        return $disk->response($path, basename($path), [
            'Cache-Control' => 'private, no-store',
            'X-Content-Type-Options' => 'nosniff',
        ], 'inline');
    }

    /**
     * Accept only generated paths inside this file kind's own directory.
     */
    private function isStaffPhotoPath(string $path): bool
    {
        if (
            $path === ''
            || str_contains($path, "\0")
            || str_starts_with($path, '/')
            || str_starts_with($path, '\\')
            || preg_match('#^[A-Za-z]:#', $path) === 1
        ) {
            return false;
        }

        $segments = preg_split('#[\\\\/]+#', $path) ?: [];

        if (in_array('..', $segments, true)) {
            return false;
        }

        if (
            ($segments[0] ?? null) !== UpdateStaffPhotoAction::DIRECTORY
            || count($segments) !== 2
        ) {
            return false;
        }

        /*
         * Photos are rendered inline on the application's own origin. Accept
         * only the exact ULID + raster-extension shape generated by the Action,
         * so a corrupted/imported row cannot point this endpoint at HTML.
         */
        return preg_match(
            '#^[0-9A-HJKMNP-TV-Z]{26}\.(?:jpg|png|webp)$#i',
            $segments[1],
        ) === 1;
    }
}
